language: objective-c
osx_image: xcode10.2

before_install:
 - brew install carthage || true
 - brew outdated carthage || brew upgrade carthage
 - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

before_script:
 - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
 - carthage bootstrap --platform tvOS --no-use-binaries --cache-builds

script:
 - xcodebuild clean build -workspace "MTG Deck Builder.xcworkspace" -scheme "MTG Deck Builder" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
