language: objective-c
osx_image: xcode10.2
script: xcodebuild clean build -workspace "MTG Deck Builder.xcworkspace" -scheme "MTG Deck Builder" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
